# Generated by Django 5.2.3 on 2026-02-12 16:56

import django.db.models.deletion
import finder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=finder.models.upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('detected_label', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('median_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_listings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_suggestion', to='finder.productimage')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('item_url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='finder.productimage')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
