# Generated by Django 6.0.2 on 2026-02-13 07:09

import finder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("refurbished", "Refurbished"),
                            ("open_box", "Open Box"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category_id", models.CharField(max_length=32)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=finder.models.upload_to
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
